[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"  # Match your local Node version
  VITE_SERVICE_ID = "service_we5v3qb"
  VITE_TEMPLATE_ID = "template_umuszdo"
  VITE_PUBLIC_KEY = "jRfGLISWyKvz_gAqZ"
  CI = "false"  # Disable CI behavior that might limit output

[context.production.environment]
  NODE_ENV = "production"